# Generated by Django 4.0.1 on 2022-01-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ph_no', models.PositiveBigIntegerField()),
                ('time', models.TextField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
            ],
        ),
    ]
