# Generated by Django 4.0.1 on 2022-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bookings', models.JSONField()),
                ('ph_no', models.PositiveBigIntegerField()),
                ('time', models.TextField(blank=True, null=True)),
                ('start', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('end', models.TextField(blank=True, null=True)),
                ('no', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
